window.PUBLIC_APP_CONFIG={
  supabase:{
    url:"https://qmjqmsujkdjfwzbavfnn.supabase.co",
    anonKey:"sb_publishable_itK_8RzkqaH_K5_KRiIq_Q_SPm_DDJC"
  },
  photos:{
    enableSharedGallery:true,
    readOnly:true,
    allowDirectUpload:false
  },
  schedule:{
    sheetUrl:"https://sheetdb.io/api/v1/x97irced8j3de",
    fields:{
      date:"date",
      title:"time",
      detail:"detail"
    }
  },
  verse:{
    sheetUrl:"https://sheetdb.io/api/v1/0z7it7x68y6xl",
    fields:{
      date:"date",
      text:"verse"
    }
  },
  cloudinary:{
    cloudName:"",
    uploadPreset:""
  }
}
