create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  url text not null,
  delete_token text,
  created_at timestamptz not null default now()
);

alter table public.photos
add column if not exists delete_token text;

alter table public.photos enable row level security;

drop policy if exists "allow read photos" on public.photos;
create policy "allow read photos"
on public.photos
for select
using (true);

drop policy if exists "allow insert photos" on public.photos;
drop policy if exists "allow delete photos" on public.photos;

-- GitHub Pages 공개 배포 기본값은 읽기 전용입니다.
-- insert/delete 정책은 추가하지 않습니다.
-- 쓰기 기능이 필요하면 인증 또는 서버 서명 방식을 먼저 붙인 뒤 별도 정책을 설계하세요.
