create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  url text not null,
  delete_token text,
  created_at timestamptz not null default now()
);

alter table public.photos
add column if not exists delete_token text;

alter table public.photos enable row level security;

drop policy if exists "allow read photos" on public.photos;
create policy "allow read photos"
on public.photos
for select
using (true);

drop policy if exists "allow insert photos" on public.photos;
create policy "allow insert photos"
on public.photos
for insert
with check (true);

drop policy if exists "allow delete photos" on public.photos;
create policy "allow delete photos"
on public.photos
for delete
using (true);
